name: ♿ Accessibility Issue
description: Report an accessibility or usability issue.
title: '[accessibility]: '
labels: 'type: accessibility, awaiting triage'
body:
  - type: markdown
    attributes:
      value: '## Welcome!'
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this accessibility report.
  - type: markdown
    attributes:
      value: Please fill in as much of the template below as you're able to. If you're unsure whether the issue already exists or how to fill in the template, open an issue anyway. Our team will help you to complete the rest.
  - type: markdown
    attributes:
      value: Your issue might already exist. If so, add a comment to the existing issue instead of creating a new one. You can [find existing issues here](https://github.com/nhsuk/nhsapp-frontend/issues).
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser(s) are you experiencing the issue?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Edge
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      multiple: true
      options:
        - Windows
        - MacOS
        - Other
  - type: input
    id: version
    attributes:
      label: NHS App Frontend version
      description: 'Which version(s) of the NHS App Frontend are you using? This can be found in your package.json file.'
      placeholder: e.g. v1.2.0
  - type: input
    id: technology
    attributes:
      label: Assistive technology
      description: 'Did you experience the issue using an assistive technology?'
      placeholder: e.g. JAWS, MacOS VoiceOver
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Tell us more about the accessibility issue that you're experiencing"
      placeholder: What did you expect to happen? What happened instead?
    validations:
      required: true
  - type: input
    id: wcag
    attributes:
      label: WCAG 2.2 Violation
      description: 'Does this violate a specific WCAG 2.2 checkpoint?'
      placeholder: e.g Success Criterion 1.4.3 Contrast (Minimum)
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: 'How do we reproduce the accessibility issue you described?'
