blank_issues_enabled: true
contact_links:
  - name: Get in touch another way
    url: https://design-system.nhsapp.service.nhs.uk/help-and-feedback/
    about: Find out how to get in touch via email or Slack.
