name: 🎨 Design defect
description: Report a visual design issue
title: '[Bug]: '
labels: 'type: bug 🐛'
body:
  - type: markdown
    attributes:
      value: '## Welcome!'
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out the details below for this design defect.
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser(s) are you experiencing the issue?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Edge
  - type: input
    id: version
    attributes:
      label: Package version
      description: 'Which version(s) are you using?'
      placeholder: e.g. v1.2.0
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Tell us more about the problem that you're running into"
      placeholder: What did you see? What did you expect to see?
    validations:
      required: true
  - type: textarea
    id: example-url
    attributes:
      label: Screenshots
      description: 'Provide screenshots of the problem'
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: 'How do we reproduce the problem displayed in the screenshots above?'
    validations:
      required: true
