name: ✨ Feature request
description: Suggest a new feature or idea
title: '[Feature request]: '
labels: 'type: feature request, awaiting triage'
body:
  - type: markdown
    attributes:
      value: '## Welcome!'
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out the details below for this new feature or idea.
  - type: markdown
    attributes:
      value: Please fill in as much of the template below as you're able to. If you're unsure whether the issue already exists or how to fill in the template, open an issue anyway. Our team will help you to complete the rest.
  - type: markdown
    attributes:
      value: Your issue might already exist. If so, add a comment to the existing issue instead of creating a new one. You can [find existing issues here](https://github.com/nhsuk/nhsapp-frontend/issues).
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Briefly describe the thing."
    validations:
      required: true
  - type: textarea
    id: Related component
    attributes:
      label: Related component
      description: 'Does this feature relate to an existing component?'
  - type: textarea
    id: Context
    attributes:
      label: Context
      description: 'What are you trying to do? Is this something you think should behave differently, or something that you currently cannot do? Is this related to an existing issue/bug?'
  - type: textarea
    id: Alternatives
    attributes:
      label: Alternatives
      description: 'Are you currently using a workaround / alternative solution instead?'
  - type: textarea
    id: Additional
    attributes:
      label: Additional information (if applicable)
      description: 'What evidence do you have that this meets the needs of users? It's useful for us to know of any user research/testing you've done with this feature.'
