name: PR checks
on:
  pull_request:
    types: [opened, synchronize, closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  linting:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run lint

  deploy-preview:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run docs:build
        env:
          ELEVENTY_PATH_PREFIX: /pr-${{ github.event.number }}

      - name: Debug build output
        run: |
          echo "=== Build directory contents ==="
          ls -la dist/docs/
          echo ""
          echo "=== Looking for index.html ==="
          find dist/docs/ -name "index.html" -type f
          echo ""
          echo "=== Sample HTML content (first 20 lines) ==="
          head -20 dist/docs/index.html || echo "No index.html found"
          echo ""
          echo "=== PR number ==="
          echo "PR number: ${{ github.event.number }}"
          echo "Destination dir will be: pr-${{ github.event.number }}"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/docs
          destination_dir: pr-${{ github.event.number }}
          keep_files: true

      - name: Debug deployment
        run: |
          echo "=== Deployment completed ==="
          echo "Expected URL: https://nhsuk.github.io/nhsapp-frontend/pr-${{ github.event.number }}/"
          echo "Files should be in gh-pages branch under: pr-${{ github.event.number }}/"

      - name: Comment PR
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const previewUrl = `https://nhsuk.github.io/nhsapp-frontend/pr-${prNumber}/`;
            const commentBody = `🚀 Preview deployed to: ${previewUrl}

            _Last updated: ${new Date().toLocaleString('en-GB', { 
              timeZone: 'Europe/London',
              year: 'numeric',
              month: 'short', 
              day: 'numeric',
              hour: '2-digit',
              minute: '2-digit'
            })}_`;

            // Find existing preview comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });

            const existingComment = comments.find(comment => 
              comment.user.login === 'github-actions[bot]' && 
              comment.body.includes('🚀 Preview deployed to:')
            );

            if (existingComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: commentBody
              });
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: commentBody
              });
            }

  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Remove preview folder
        run: |
          rm -rf pr-${{ github.event.number }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Remove preview for PR #${{ github.event.number }}" || exit 0
          git push
