name: Publish to NPM
on:
  release:
    types:
      - published
jobs:
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm ci

      - name: Build release package
        run: npm run release

      - name: Get package version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: github.event.release.tag_name
          VERSION: steps.get_version.outputs.VERSION
        run: gh release upload "$TAG" "./dist/nhsapp-frontend-$VERSION.zip"

      - name: Publish npm package
        if: ${{ !github.event.release.prerelease }}
        run: npm publish --tag latest

      - name: Publish npm package (pre-release)
        if: ${{ github.event.release.prerelease }}
        run: npm publish --tag next
